server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false # Сервер сам себя не регистрирует
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # Для ускорения старта в разработке
